Learn NumPy

In [2]:
import numpy as np
# print(np.__version__)

In [38]:
arr1 = np.array([1,2,3])
print(arr1)
print(arr1[0] + arr1[2])

[1 2 3]
4


In [ ]:
mat = np.array([[[1, 2, 3], [4, 5.5, 6]], [[7, 8, 9], [10, 11, 12]]])
mat

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# mat.ndim
# mat.shape
# mat.size
# mat.dtype
# mat.itemsize
# mat.nbytes
# print(mat[0, 1, 2])

6


In [3]:
arr_1d = np.array([1,2,3,4,5,6])
print("1D array: ",arr_1d)


1D array:  [1 2 3 4 5 6]


In [ ]:

arr_3d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_3d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [65]:
print(arr[1, -1])

10


In [4]:
import time
start = time.time()
py_list = [i*2 for i in range(100000)]
print('\n List Ops time: ', time.time()-start)

start = time.time()
np_array = np.arange(100000) *2
print('\n NumPy Ops time: ', time.time()-start)


 List Ops time:  2.0364067554473877

 NumPy Ops time:  0.0010750293731689453


In [32]:
a = np.array([1, 2, 3, 4], ndmin=5)
a

array([[[[[1, 2, 3, 4]]]]])

In [33]:
a.ndim

5

In [5]:
zeros = np.zeros((3,4))
print("zeros array: \n", zeros)

ones = np.ones((3,4))
print("zeros array: \n", ones)

full = np.full((3,3),9)
print('full array: \n', full)

random =  np.random.random((2,3))
print('random arr:\n',random)

sequence = np.arange(0, 10, 2)
print('sequence arr:\n',sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
zeros array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[9 9 9]
 [9 9 9]
 [9 9 9]]
random arr:
 [[0.6222143  0.24888147 0.8012172 ]
 [0.08740677 0.17374383 0.11791231]]
sequence arr:
 [0 2 4 6 8]


In [6]:
vector = np.array([1,2,3])
print('Vector:\n',vector)
matrix = np.array([[1,2,3],[1,2,3]])
print('Matrix:\n',matrix)
tensor = np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
print('Tensor:\n',tensor)

Vector:
 [1 2 3]
Matrix:
 [[1 2 3]
 [1 2 3]]
Tensor:
 [[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


Arrays Properties


In [7]:
arr = np.array([[1,2,3],[1,2,3],[4,5,6]])
print('Matrix:\n',matrix)
print('Shape:\n', arr.shape)
print('Dimension:\n', arr.ndim)
print('Size:\n', arr.size)
print('Data Type:\n', arr.dtype)



Matrix:
 [[1 2 3]
 [1 2 3]]
Shape:
 (3, 3)
Dimension:
 2
Size:
 9
Data Type:
 int64


Array Reshaping


In [8]:
arr = np.arange(12)
print('Orinignal Array: \n', arr)

reshaped = arr.reshape((3, 4))
print('Reshaped Array: \n', reshaped)

flattened = reshaped.flatten()  #It store copy
print('flattened Array: \n', flattened)

Raveled = reshaped.ravel()      # It returns view
print('Raveled Array: \n', Raveled)

#Transpose
transpose =  reshaped.T
print('Transpose: \n', transpose)

Orinignal Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [4]:
import numpy as np
print(np.__version__)


2.2.6
