In [4]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
 

In [3]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 =  np.random.rand(3,3)
array3 =  np.zeros((4,4))
print('\n\n',array1,'\n\n',array2,'\n\n',array3)



 [[1 2 3]
 [4 5 6]] 

 [[0.57164307 0.91286809 0.64981914]
 [0.61888377 0.54707981 0.08761518]
 [0.58704632 0.63721595 0.10603966]] 

 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
np.save('array1.npy',array1)
np.save('array2.npy',array2)
np.save('array3.npy',array3)

In [30]:
loaded_arr = np.load('array1.npy')
print(loaded_arr)

[[1 2 3]
 [4 5 6]]


In [7]:
try:
    # logo = mpimg.imread('numpy-logo.png')
    logo = np.load('numpy-logo.npy', allow_pickle=True)
    
    #Display
    plt.figure(figsize=(10,5))
    plt.subplot(121)
    plt.imshow(logo)
    plt.title('NumPy Logo')
    plt.grid(False)

    dark_logo = 1 - logo
    plt.subplot(122)
    plt.imshow(dark_logo)
    plt.title('NumPy Dark Logo')
    plt.grid(False)

except FileNotFoundError:
    print("NumPy Logo file not found")

NumPy Logo file not found
