In [2]:
import numpy as np


In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print('Basic Indexing:', arr[2:7])
print('with step:', arr[2:8:2])
print('Negative Indexing:', arr[-3])

Basic Indexing: [3 4 5 6 7]
with step: [3 5 7]
Negative Indexing: 8


In [13]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Get the first row
row_slice = matrix[0, :] # Result: [1, 2, 3]

# Get the second column
col_slice = matrix[:, 1] # Result: [2, 5, 8]

# Get a sub-matrix (rows 0-1, columns 1-2)
sub_matrix = matrix[0:2, 1:3]
print(sub_matrix)


[[2 3]
 [5 6]]


In [4]:
arr_2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Element:', arr_2[1,1])
print('Entire row:', arr_2[0])
print('Entire Column:', arr_2[0:,1])

Element: 5
Entire row: [1 2 3]
Entire Column: [2 5 8]


In [ ]:
# arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# print(arr[1, 1:4])


arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

arr.shape


[[2 3 4]
 [7 8 9]]


(2, 5)

### **Sorting**



In [35]:
unsorted = np.array([[3,1],[1,3],[2,2]])
np.sort(unsorted,  axis=0)



array([[1, 1],
       [2, 2],
       [3, 3]])

In [17]:
unsorted = np.array([3,5,7,9,2,1,4,0])
print(f'Sorted Array:, {np.sort(unsorted)}')

unsorted_2d = np.array([[3,1],[1,3],[2,2]])
print(f'Sorted 2D Array:\n {np.sort(unsorted_2d, axis=0)}')


Sorted Array:, [0 1 2 3 4 5 7 9]
Sorted 2D Array:
 [[1 1]
 [2 2]
 [3 3]]


### Filter


In [38]:
num = np.array([1,2,3,4,5,6,7,8,9,10])
even_num = num[num%2==0]
print(f'Even Number:\n {even_num}')


Even Number:
 [ 2  4  6  8 10]


Filter with Mask

In [ ]:
num = np.array([1,2,3,4,5,6,7,8,9,10])
mask = num > 5
print('Numbers greater then 5: ', num[mask])



Numbers greater then 5:  [ 6  7  8  9 10]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Fancy Indexing OR where()

In [24]:
num = np.array([1,2,3,4,5,6,7,8,9,10])
indices = [0,2,4]
print(num[indices])

where_res = np.where(num > 5)
print(where_res)
print(f'NP where : ',num[where_res])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where :  [ 6  7  8  9 10]


In [26]:
#                condition , True , False.
cond_res = np.where(num > 5, num*2, num)
cond_res_2 = np.where(num > 5, True, False)
print(cond_res)
print(cond_res_2)

[ 1  2  3  4  5 12 14 16 18 20]
[False False False False False  True  True  True  True  True]


Adding And Removing Data


In [31]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined  = np.concatenate((arr1,arr2))  # add like a string
combined2  = arr1+arr2
print(combined)
print(combined2)

[1 2 3 4 5 6]
[5 7 9]


#Array Compability

In [39]:
#Array Compability

a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([1,2,3,4])

print(f'Compability shape: {a.shape == b.shape or b.shape == c.shape}')



Compability shape: True


In [45]:
orig = np.array([[1,2],[3,4]])
new_row = np.array([[5,6],[7,8]])

new_arr = np.hstack((orig, new_row))
print(orig,'\n +')
print(new_row,'\n =')
print(new_arr)

[[1 2]
 [3 4]] 
 +
[[5 6]
 [7 8]] 
 =
[[1 2 5 6]
 [3 4 7 8]]


In [42]:
orig = np.array([[1,2],[3,4]])
new_col = np.array([[5],[6]])

new_arr = np.hstack((orig, new_col))
print(orig,'\n +')
print(new_col,'\n =')
print(new_arr)

[[1 2]
 [3 4]] 
 +
[[5]
 [6]] 
 =
[[1 2 5]
 [3 4 6]]


In [58]:
arr =np.array ([1,2,3,4,5])
deleted  =  np.delete (arr, 2)
print('It delete after given element: ',deleted,arr[2])

It delete after given element:  [1 2 4 5] 3
